Repository plugwise/plugwise-beta, pull requests merged in 2020-06, with the labels that each got.

#82 P1 interval
  custom_components/plugwise-beta/sensor.py
Labels: enhancement, invalid, needs_upstreaming

#81 Changes as per 36406
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/binary_sensor.py
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/sensor.py
  custom_components/plugwise-beta/switch.py
Labels: downstreaming

#85 Add discovery and config_flow options
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/config_flow.py
  custom_components/plugwise-beta/manifest.json
  custom_components/plugwise-beta/strings.json
  custom_components/plugwise-beta/translations/en.json
  custom_components/plugwise-beta/translations/nl.json
Labels: enhancement, needs_upstreaming

#87 Allow discovery of multiple devices (not cross domain)
  custom_components/plugwise-beta/config_flow.py
Labels: bug, enhancement
