Repository plugwise/plugwise-beta, pull requests merged in 2020-04, with the labels that each got.

#15 Doc updates
  README.md
  TODO.md
Labels: documentation

#16 Version bump and black
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/manifest.json
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#17 Update for Smile v0.0.57
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/const.py
  custom_components/plugwise-beta/manifest.json
  custom_components/plugwise-beta/switch.py
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#18 Public beta 0.1.0
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/manifest.json
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#19 v0.1.2 Fix LINT issues, correct api public vars, cleanup
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/config_flow.py
  custom_components/plugwise-beta/manifest.json
  custom_components/plugwise-beta/manifest.json.ha-core
  custom_components/plugwise-beta/sensor.py
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#34 Rework device registry
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/binary_sensor.py
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/sensor.py
  custom_components/plugwise-beta/switch.py
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#36 Use the added schedule_temperature to program and show the schedule-setpoint when activating a schedule
  custom_components/plugwise-beta/climate.py
Labels: enhancement

#37 Device mapping to "Auxiliary Device" (short Auxiliary)
  custom_components/plugwise-beta/binary_sensor.py
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/sensor.py
  custom_components/plugwise-beta/switch.py
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#39 Merge heater_central into gateway
  custom_components/plugwise-beta/binary_sensor.py
  custom_components/plugwise-beta/sensor.py
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#40 Dont copy-paste, fix naming
  custom_components/plugwise-beta/water_heater.py
Labels: bug, enhancement

#41 Devicenames2
  custom_components/plugwise-beta/binary_sensor.py
  custom_components/plugwise-beta/sensor.py
  custom_components/plugwise-beta/water_heater.py
Labels: enhancement

#43 PR Cleanup
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/config_flow.py
Labels: enhancement

#45 Requestfix counterpart
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/manifest.json
  custom_components/plugwise-beta/strings.json
  custom_components/plugwise-beta/translations/en.json
  custom_components/plugwise-beta/translations/nl.json
Labels: bug, enhancement

#44 Release 0.2.0
  README.md
  custom_components/plugwise-beta/binary_sensor.py
  custom_components/plugwise-beta/climate.py
  custom_components/plugwise-beta/manifest.json
  custom_components/plugwise-beta/manifest.json.ha-core
  custom_components/plugwise-beta/sensor.py
  custom_components/plugwise-beta/switch.py
Labels: documentation, enhancement

#46 Add warning to README to make it more obvious for HACS users
  README.md
Labels: documentation

#50 Add debug and user preelease for #49
  custom_components/plugwise-beta/__init__.py
  custom_components/plugwise-beta/manifest.json
Labels: bug, help wanted
