Repository plugwise/plugwise-beta, pull requests merged in 2023-09, with the labels that each got.

#464 Cache bump to clear PR backlog
  .github/workflows/test.yml
Labels: bug

#466 Revert typing now that were native typed
  .github/workflows/test.yml
  scripts/core-testing.sh
Labels: downstreaming

#467 Update teams structure
  CODEOWNERS
Labels: documentation

#480 Improve warning through issue creation on Core DEV (RC/Beta) commits
  .github/workflows/core_next.yml
  .github/workflows/test.yml
Labels: quality, github-actions

#489 Adding entity_registry cleaning
  CHANGELOG.md
  custom_components/plugwise/__init__.py
  custom_components/plugwise/binary_sensor.py
  custom_components/plugwise/climate.py
  custom_components/plugwise/const.py
  custom_components/plugwise/coordinator.py
  custom_components/plugwise/number.py
  custom_components/plugwise/select.py
  custom_components/plugwise/sensor.py
  custom_components/plugwise/switch.py
  custom_components/plugwise/util.py
  tests/components/plugwise/test_init.py
Labels: enhancement
