Repository plugwise/plugwise-beta, pull requests merged in 2023-08, with the labels that each got.

#447 Fix DeviceInfo Mypy and Cache version bump
  .github/workflows/test.yml
  custom_components/plugwise/entity.py
Labels: bug, downstreaming

#452 Add branch defaulting suggestions
  .github/workflows/test.yml
  .pre-commit-config.yaml
  scripts/core-testing.sh
Labels: quality

#449 Further lining up with Core Plugwise
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  custom_components/plugwise/__init__.py
  custom_components/plugwise/binary_sensor.py
  custom_components/plugwise/climate.py
  custom_components/plugwise/config_flow.py
  custom_components/plugwise/const.py
  custom_components/plugwise/entity.py
  custom_components/plugwise/number.py
  custom_components/plugwise/select.py
  custom_components/plugwise/sensor.py
  custom_components/plugwise/strings.json
  custom_components/plugwise/switch.py
  scripts/core-testing.sh
Labels: downstreaming, quality
