Repository plugwise/plugwise-beta, pull requests merged in 2024-06, with the labels that each got.

#657 Temporary fix mypy for master
  scripts/core-testing.sh
Labels: bug

#654 Update README.md
  README.md
Labels: ideas

#662 Revert as per #656
  scripts/core-testing.sh
Labels: bug, dependencies

#668 Implement various new Core features
  CHANGELOG.md
  custom_components/plugwise/__init__.py
  custom_components/plugwise/binary_sensor.py
  custom_components/plugwise/button.py
  custom_components/plugwise/climate.py
  custom_components/plugwise/config_flow.py
  custom_components/plugwise/const.py
  custom_components/plugwise/diagnostics.py
  custom_components/plugwise/entity.py
  custom_components/plugwise/number.py
  custom_components/plugwise/select.py
  custom_components/plugwise/sensor.py
  custom_components/plugwise/switch.py
Labels: downstreaming

#671 Refactor runtime-update/remove related code
  CHANGELOG.md
  custom_components/plugwise/binary_sensor.py
  custom_components/plugwise/button.py
  custom_components/plugwise/climate.py
  custom_components/plugwise/coordinator.py
  custom_components/plugwise/manifest.json
  custom_components/plugwise/number.py
  custom_components/plugwise/select.py
  custom_components/plugwise/sensor.py
  custom_components/plugwise/switch.py
  tests/components/plugwise/test_init.py
Labels: quality
