Repository plugwise/plugwise-beta, pull requests merged in 2024-08, with the labels that each got.

#695 Rework pre-commit prettier to biome
  .pre-commit-config.yaml
Labels: enhancement, dependencies

#702 Add battery_state binary_sensor for battery powered devices
  CHANGELOG.md
  custom_components/plugwise/binary_sensor.py
  custom_components/plugwise/const.py
  custom_components/plugwise/manifest.json
  custom_components/plugwise/strings.json
  custom_components/plugwise/translations/en.json
  custom_components/plugwise/translations/nl.json
  tests/components/plugwise/fixtures/m_adam_cooling/all_data.json
  tests/components/plugwise/fixtures/m_adam_heating/all_data.json
  tests/components/plugwise/fixtures/m_adam_jip/all_data.json
  tests/components/plugwise/fixtures/m_adam_multiple_devices_per_zone/all_data.json
  tests/components/plugwise/snapshots/test_diagnostics.ambr
  tests/components/plugwise/test_init.py
Labels: enhancement, needs_upstreaming

#700 Intermediate Core downstream / prepare tagging upstream
  CHANGELOG.md
  custom_components/plugwise/__init__.py
  custom_components/plugwise/binary_sensor.py
  custom_components/plugwise/button.py
  custom_components/plugwise/climate.py
  custom_components/plugwise/config_flow.py
  custom_components/plugwise/const.py
  custom_components/plugwise/coordinator.py
  custom_components/plugwise/diagnostics.py
  custom_components/plugwise/entity.py
  custom_components/plugwise/manifest.json
  custom_components/plugwise/number.py
  custom_components/plugwise/select.py
  custom_components/plugwise/sensor.py
  custom_components/plugwise/switch.py
  custom_components/plugwise/util.py
  hacs.json
  pyproject.toml
Labels: enhancement, needs_upstreaming, downstreaming
