Repository plugwise/plugwise-beta, pull requests merged in 2025-02, with the labels that each got.

#824 Remove user-configuration of port
  CHANGELOG.md
  custom_components/plugwise/config_flow.py
  tests/components/plugwise/test_config_flow.py
Labels: require-dev-pass

#825 v0.57.0 release
  CHANGELOG.md
  custom_components/plugwise/manifest.json
Labels: require-dev-pass

#829 Implement HA Core PR 138039
  CHANGELOG.md
  custom_components/plugwise/__init__.py
  custom_components/plugwise/binary_sensor.py
  custom_components/plugwise/button.py
  custom_components/plugwise/climate.py
  custom_components/plugwise/coordinator.py
  custom_components/plugwise/diagnostics.py
  custom_components/plugwise/number.py
  custom_components/plugwise/select.py
  custom_components/plugwise/sensor.py
  custom_components/plugwise/switch.py
Labels: downstreaming

#831 Fix build failure indication (more) properly
  .github/workflows/test.yml
Labels: bug

#834 Bugfix for Issue 833
  CHANGELOG.md
  custom_components/plugwise/config_flow.py
  custom_components/plugwise/manifest.json
  pyproject.toml
Labels: bug
